set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CXX_OPTIONS "")
set(LINKER_OPTIONS "")

if(MSVC)
  # 8 → 64 bits
  # 4 → 32 bits
  if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    add_definitions(-DWIN64)
  else()
    add_definitions(-DWIN32)
  endif()
  if(NOT DEFINED IS_DEBUG OR IS_DEBUG EQUAL 0)
    set(CXX_OPTIONS "/O2 /Zi /W3 /Gd /Gy /GS /Oi /MD /FC /EHsc")
    set(LINKER_OPTIONS "/DEBUG /INCREMENTAL")
  else()
    set(CXX_OPTIONS "/Od /Zi /W3 /Gd /GS /MDd /FC /EHsc")
    set(LINKER_OPTIONS "/INCREMENTAL:NO")
  endif()
  add_definitions(-D_SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING)
else()
  if(NOT DEFINED IS_DEBUG OR IS_DEBUG EQUAL 0)
    set(CXX_OPTIONS "-O3 -fstack-protector-all -D_FORTIFY_SOURCE=2 -ffunction-sections -Wall -Werror -std=c++${CMAKE_CXX_STANDARD}")
  else()
    set(CXX_OPTIONS "-Wall -Og -g -std=c++${CMAKE_CXX_STANDARD}")
    # GCOV
    set(CXX_OPTIONS "${CXX_OPTIONS} --coverage")
  endif()
endif()

add_definitions(-DNOMINMAX)
if(NOT DEFINED IS_DEBUG OR IS_DEBUG EQUAL 0)
  add_definitions(-DNDEBUG)
else()
  add_definitions(-DDEBUG)
  add_definitions(-D_DEBUG)
endif()

set(CMAKE_CXX_FLAGS "${CXX_OPTIONS}")
set(CMAKE_EXE_LINKER_FLAGS "${LINKER_OPTIONS}")
