sudo: false		
language: cpp
compiler:
    - gcc
dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq gcc-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - "[ $CC = gcc ] && export CC=gcc-7 || true"
script:
  - make
  - make test
