# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install cmake
            cmake --version
            gcc --version
      - name: Configure for DEBUG
        shell: bash
        run: cmake -DDISTRIBUTION=debug .
      - name: --DEBUG-- Build
        shell: bash
        run: make
      - name: --DEBUG-- Run gtest
        shell: bash
        run: |
            chmod +x ./bin/hex2bin_gtest
            ./bin/hex2bin_gtest
      - name: --DEBUG-- Run test
        shell: bash
        run: |
            chmod +x ./test
            ./test
      - name: Configure for RELEASE
        shell: bash
        run: cmake -DDISTRIBUTION=release .
      - name: --RELEASE-- Build
        shell: bash
        run: make
      - name: --RELEASE-- Run test
        shell: bash
        run: |
            chmod +x ./test
            ./test
