# This is a basic workflow to help you get started with Actions

name: Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Windows 2022 MSVC
    # The type of runner that the job will run on
    runs-on: windows-2022
    env:
      CMAKE_GENERATOR: "Visual Studio 17 2022"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            choco install python3
            python --version
      - name: Configure for debug
        shell: bash
        run: cmake -S . -B build -DDISTRIBUTION=debug -G "${{ env.CMAKE_GENERATOR }}"
      - name: Build debug
        shell: bash
        run: cmake --build build
      - name: Run gtest
        shell: bash
        run: |
            ./bin/hex2bin_gtest.exe
      - name: Run test
        shell: bash
        run: |
            python test.py --file bin/hex2bin.exe
      - name: Configure for release
        shell: bash
        run: cmake -S . -B build -DDISTRIBUTION=release -G "${{ env.CMAKE_GENERATOR }}"
      - name: Build release
        shell: bash
        run: cmake --build build
      - name: Run test
        shell: bash
        run: |
            python test.py --file bin/hex2bin.exe

